services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: todo_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todo_app
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Laravel Backend API
  backend:
    build: ./backend
    container_name: todo_backend
    ports:
      - "8000:80"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_DATABASE=todo_app
      - DB_USERNAME=todo_user
      - DB_PASSWORD=todo_password
    depends_on:
      - mysql

  # React Frontend
  frontend:
    build: ./frontend
    container_name: todo_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data:

